nightingaleproject/vital-records-dotnet

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs, projects/VitalRecord/OtherURLs.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
Adds:
1. Father ID fields (name, SSN)
2. Mother and father birth location fields
3. Mother residence and mailing address fields
=> feat(bfdr): id, name and address fields

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
Date of registration, date of first prenatal care visit, and date of last period
=> feat(bfdr): implement date fields

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/fixtures/json/BasicBirthRecord.json, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/BirthRecord_fieldsAndCreateMethods.cs, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
Ticket 568, Marital Status, Married During Pregnancy, Paternity Acknowledgement, Mother Transferred, Infant Living, Infant Transferred, Number of Live Born, and SSN Requested for Child.
Refactored the Observation helpers to allow us to get and create observations with different value types. Moved Marc's initial helper functions to VitalRecord_util.cs
=> 568 married transferred ssn

projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs
Add support for APGAR properties
Fix a bug in the cigarettes smoked annotations
=> feat(bfdr): add apgar five and ten minute scores

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/fixtures/json/BirthRecordFakeWithRace.json, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/BirthRecord_fieldsAndCreateMethods.cs, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs
support for emerging issues fields
=> feat(bfdr): implement emerging issues

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/fixtures/json/BasicBirthRecord.json, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs, projects/VitalRecord/CodeSystems.cs, projects/VitalRecord/VitalRecord.xml
Implements missing BirthRecord fields:
ITRAN
TRAN
PRES
TLAB
NPCES
NPCES_BPASS
=> feat(bfdr): Nvss 600 missing fields

projects/BFDR/README.md
Adds a readme to the BFDR project
=> docs(bfdr): BFDR readme

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs
This pull request
1. Adds a file `IJEFetalDeath.cs` that provides blank implementations for every fetal death IJE field
2. Adds a file `FetalDeathRecord.cs` that provides an empty placeholder for the FetalDeathRecord class (needed for IJEFetalDeath to build)
=> feat(bfdr): Add outline of IJE and record support for fetal death

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs
Fetal Death Cause or Condition Part 2
COD18a9 through COD18a14
=> feat(bfdr): implement more fetal death cause or conditions

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs
Tickets 608 and 609 (Other cause or conditions part 1 and 2)
COD18b1 through COD18b7
COD18b8 through COD18b14
=> feat(bfdr): Implement other significant fetal death cause or conditions

projects/BFDR.CLI/BFDR.CLI.csproj, projects/BFDR.Messaging/BFDR.Messaging.csproj, projects/BFDR.Tests/BFDR.Tests.csproj, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BFDR.csproj, projects/BFDR/BFDR.xml, projects/BFDR/CHANGELOG.md, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/Canary/Canary.csproj
weight editflag codes were misused/tested in BFDR for birth weight and pre-pregnancy weight
Read me seemed to suggest that the changelog gets updated automatically. Let me know if I need to add anything.
=> fix(bfdr): correcting editflag weight codes

projects/BFDR/BFDR.csproj, projects/BFDR/CHANGELOG.md
This PR fixes the format of the bfdr version number
=> fix(bfdr): fix version number format

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs
implements fetal presentation, estimation of gestation (+edit flag), was placental exam performed?, ICU admission, trial of labor attempted, method of disposition, and route/method of delivery.
=> feat(bfdr): misc fetal death fields

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/IJEFetalDeath.cs
Was already implemented in Natality, so just needed to add tests and IJE methods for fetal death.
=> feat(bfdr): mother and father education 

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/IJEFetalDeath.cs
DLMP_YR, DLMP_MO, DLMP_DY - Already implemented in natality, just added test cases
=> feat(bfdr): implement support for fetal death last menstrual period date

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs
Implement WIC food, number of births living/dead, and fetal deaths this delivery
=> Nvss 623 wic previous births

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord.json, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/IJENatality.cs, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
Implement fetus name and parent age at delivery for fetal death case
=> Nvss 628 age fetus name

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs
Implement mother's birth place and residence fields for fetal death:
BPLACEC_ST_TER
MBPLACE_ST_TER_TXT
BPLACEC_CNT
MBPLACE_CNTRY_TXT
STATEC
COUNTRYC
LIMITS
STATETXT
CNTRYTXT
COUNTYC
STNUM
PREDIR
STNAME
POSTDIR
APTNUMB
ADDRESS
ZIPCODE
COUNTYTXT
CITYTXT
=> Nvss 630 mother birthplace

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/IJEFetalDeath.cs
Name fields and SSN for Mother and Father were already implemented in Natality, so just needed to add tests and IJE methods for fetal death.
=> feat(bfdr): implement mother and father name and ssn for fetal death

README.md, projects/BFDR.Messaging/BFDR.Messaging.csproj, projects/VitalRecord/IJE.cs
Adds the latest bfdr package info to the project README. Bumped the BFDR.Messaging version to release v1.0.0-preview.3. This version should have been released along with BFDR v1.0.0-preview.3.
=> docs: add bfdr packages to project readme

projects/BFDR.CLI/Program.cs
update bfdr cli to use yesnounknown vs instead of the old value set hispanicnounknown
=> fix(bfdr): update bfdr cli to use yesnounknown 

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/NatalityRecord_submissionProperties.cs
Implements the patient fetal death extension on the fetal-death-feature branch. No IJE mapping
=> feat(bfdr): implement patient fetal death extension

projects/Canary/Models/BirthRecordFaker.cs
Add randomized fields or expanded randomization for industry/occupation, education level, mother/infant medical record number, place of birth, birth jurisdiction, abnormal conditions of newborn, labor characteristics, maternal morbidities, infections, congenital anomalies, risk factors, Apgar, birthweight, mother height and weight, cigarettes smoked, WIC food
=> feat(canary): randomize bfdr record generation

projects/Canary/Models/DeathRecordFaker.cs
See [canary#276](https://github.com/nightingaleproject/canary/issues/276).
=> fix: updating age at death agetype format

projects/BFDR.Messaging/BFDR.Messaging.csproj, projects/BFDR/BFDR.csproj, projects/BFDR/CHANGELOG.md
Update version for new bfdr release v1.0.0-preview.8
=> docs(bfdr): update docs for release v1.0.0-preview.8

projects/Canary/ClientApp/src/components/tests/FHIRMessageProducing.js, projects/Canary/ClientApp/src/components/tests/MessageConnectathonProducing.js, projects/Canary/ClientApp/src/components/tools/FHIRMessageCreator.js, projects/Canary/ClientApp/src/components/tools/FHIRMessageSyntaxChecker.js, projects/Canary/ClientApp/src/components/tools/MessageInspector.js, projects/Canary/ClientApp/src/data.js, projects/Canary/Models/CanaryBirthMessage.cs, projects/Canary/Models/CanaryFetalDeathMessage.cs
This PR adds Fetal Death Messaging support to Canary
=> feat(canary): added fetal death messaging to canary

projects/BFDR.Tests/IJEFetalDeath_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs, projects/VRDR/DeathRecord.xml, projects/VRDR/IJEMortality.cs, projects/VitalRecord.Messaging/CommonMessage.cs, projects/VitalRecord/IJE.cs, projects/VitalRecord/VitalRecord.xml
This PR implements the VOID flag for Birth and Fetal Death. Void will default to 0 (not void). This PR includes a light refactoring of IJEMortality's Void for common code usage.
=> feat(bfdr): 732 implements void flag for birth/fetaldeath

projects/BFDR.Tests/BFDR.Tests.csproj, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord_constructors.cs, projects/BFDR/FetalDeathRecord_responseOnlyProperties.cs, projects/BFDR/NatalityRecord_constructors.cs
This pull request adds or updates implementations and tests for
* GetDemographicCodedContentBundle
* GetCodedCauseOfFetalDeathBundle
* GetCodedIndustryAndOccupationBundle
=> feat(bfdr): 735 Implement GetBundle methods for Coded Responses in BFDR

projects/VRDR.Messaging/VRDR.Messaging.csproj, projects/VRDR/CHANGELOG.md, projects/VRDR/VRDR.csproj
add change log and set VRDR version number to 5.1.0-preview.1
=> docs(vrdr): add changelog to vrdr

projects/VRDR.CLI/1.json, projects/VRDR.CLI/1_wJurisdiction.json, projects/VRDR.CLI/Program.cs, projects/VRDR.CLI/Program_convert.cs, projects/VRDR.CLI/Program_urimaps.cs, projects/VRDR.CLI/Program_util.cs, projects/VRDR.STU2.Convert/1.json, projects/VRDR.STU2.Convert/Program.cs, projects/VRDR.STU2.Convert/README.md, projects/VRDR.STU2.Convert/VRDR.STU2.Convert.csproj, projects/VRDR.STU2.Convert/VRDR.STU2.Convert.sln
Add new VRDR.STU2.Convert project that reuses some files from VRDR.CLI to implement roundtrip conversion between STU2 and STU3. Refactors VRDR.CLI to extract version independent functionality that can be built into applications that are using either STU2 or STU3 versions of the VRDR library.
Fixes #NVSS-767
=> feat(vrdr): add new project to illustrate roundtripping from STU2 via STU3 and back to STU2

.gitignore, projects/VitalRecord.Tests/BundleTypeException_Should.cs, projects/VitalRecord.Tests/IJE_Should.cs, projects/VitalRecord.Tests/Mappings_Should.cs, projects/VitalRecord.Tests/README.md, projects/VitalRecord.Tests/ValueSets_Should.cs, projects/VitalRecord.Tests/VitalRecord.Tests.csproj, projects/VitalRecord.Tests/VitalRecord.Tests.sln, projects/VitalRecord.Tests/VitalRecord_Should.cs, projects/VitalRecord/BundleTypeException.cs, projects/VitalRecord/IJE.cs, projects/VitalRecord/VitalRecord.xml
Additional tests to fill-in holes in test coverage of the vr-dotnet library.
Closes: #NVSS-764
=> test(vr): additional tests for vr-dotnet library classes

projects/BFDR.Tests/Connectathon_Should.cs, projects/BFDR.Tests/Mappings_Should.cs, projects/BFDR.Tests/README.md, projects/BFDR.Tests/ValueSets_Should.cs
=> test(bfdr): add tests for Connectathon, Mappings and ValueSets classes

projects/VRDR.Tests/DeathRecord_Should.cs, projects/VRDR.Tests/Messaging_Should.cs, projects/VRDR.Tests/MortalityData_Should.cs, projects/VRDR/DeathRecord.xml, projects/VRDR/DeathRecord_submissionProperties.cs, projects/VRDR/IJEMortality.cs, projects/VRDR/README.md
=> feat(vrdr): implement coded occupation and industry
