projects/BFDR.CLI/BirthRecord.CLI.csproj, projects/BFDR.CLI/Program.cs, projects/BFDR.Tests/BirthRecord.Tests.csproj, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/fixtures/json/BirthRecordFake.json, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_submissionProperties.cs
Added features:
Fake record
Json2xml
checkXml
checkJson
Xml2json
Xml2xml
Json2json
Roundtrip-ije
Roundtrip-all
Ije
Ijebuilder
Compare
Extract
Added singleordefault() to suffix to avoid error in getter
Added todo's to address issues/STU updates
Remaining Issues
Race and ethnicity getter returns empty codeabledict when nothing is present, which causes json2json and xml2xml to generate a bunch of empty race/ethnicity entries that should be “no” or not present at all
Roundtrip-ije which includes whitespace on occasion and flips Y’s to N’s in some cases
=> Nvss 579 cli feature updates

projects/BFDR.CLI/Program.cs, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
This pull request:
1) Adds GetObservationValueHelper and SetObservationValueHelper methods to make it easier to implement property helpers for records
2) Adds GetObservationValue and SetObservationValue methods to make it easier to implement properties that set coded values in observations; useful feedback would be on whether generalizing this to other observation value types makes sense, and if so what a good approach would be
3) Implements support for BFDR mother and father education level and education level edit flag properties
4) Adds some generalized support for testing properties that take coded values based on value sets along with their helper functions
=> feat(bfdr): add support for BFDR mother and father education level plus property helpers

projects/VRDR/DeathRecord.xml, projects/VRDR/ValueSets.cs, projects/VitalRecord/ValueSets.cs, projects/VitalRecord/VitalRecord.xml, scripts/README.md, scripts/generate_value_set_lookups.rb
This pull request
1. Updates the generate_value_set_lookups.rb script to skip value sets with no codes
2. Updates the generate_value_set_lookups.rb script to add a display value for a code that's missing one
3. Updates the various ValueSets.cs files with the new results of running the updated script
4. Updates the scripts directory README to reflect the most recent status of the scripts
=> feat: Clean up value set code file generation

projects/BFDR.Tests/BirthRecord.Tests.csproj, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_submissionProperties.cs, projects/BFDR/IJENatality.cs
Because HIN (height inches) and HFT (height feet) both map to a single FHIR field, both IJE setters take height in inches. This seemed like the most parsimonious solution - open to feedback on a different implementation. See the tests in `NatalityData_should` for how it looks in practice.
=> Nvss 565 mother height

projects/BFDR/BirthRecord_submissionProperties.cs
I checked all fields where GetOrCreateObservation or UpdateEntry (also calls subjectID()) was used. Using the debugger, I validated that the correct FHIR subjects were being assigned
=> fix(bfdr): add FHIRSubject annotation for InfantLiving and SSNRequested

projects/BFDR/BirthRecord_submissionProperties.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs, projects/bfdr-dotnet.sln
This PR refactors the BFDR partial date time helper methods to be cleaner, more readable, and removes duplicated code. Now, each of the SetDay/SetMonth/SetYear fields delegate to a BuildFhirDateTime() method which builds a new FhirDateTime which is mostly agnostic of what date element type calls it.
=> feat(bfdr): PartialDateTime refactor

projects/BFDR.Tests/fixtures/json/BirthRecordDemographicsCodingUpdateMessage.json, projects/BFDR.Tests/fixtures/json/RaceEthnicityCaseRecord.json, projects/BFDR.Tests/fixtures/json/RaceEthnicityCaseRecord2.json, projects/BFDR/BirthRecord.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/BirthRecord_fieldsAndCreateMethods.cs, projects/BFDR/BirthRecord_submissionProperties.cs
Constructors: removing comments to birth constructors, adding others.
Removed race/ethnicity fields and create methods and replaced with getOrCreateObservation helper.
Am getting two types of errors:
1. One is an exception I put in, so it might be that I should just cut it out. In BirthRecord_constructors, `GetDemographicCodedContentBundle()` was returning a bundle with no composittion (a required field) so I added it along with the required mother or father sections. If there is no mother or father to report on, it seems like a pointless record, so I have it raise the exception. Is this pre-emptive validation inappropriate?
2. The other is a null reference exception in the `SubjectId()` method in fieldsAndCreateMethods. When I switched to using the getOrCreateObservation method for …
=> refactor(bfdr): constructor clean up

projects/BFDR/NatalityRecord_submissionProperties.cs, projects/Canary/ClientApp/src/components/Navigation.js, projects/Canary/ClientApp/src/components/misc/info/Property.js, projects/Canary/ClientApp/src/components/misc/info/Types/CheckboxType.js, projects/Canary/ClientApp/src/components/tests/FHIRIJEValidatorProducing.js, projects/Canary/Controllers/RecordsController.cs, projects/VitalRecord/VitalRecord_util.cs
This PR adds support for Checkbox fields in Canary. It also reorders fields to match the checkbox ordering.
Checkboxes: Checkbox fields, such as Pregnancy Risk Factors will render as checkboxes rather than true/false. They've also had their priorities reordered so that they display in the expected order, where "grouped" sections (which cannot be programmatically grouped at this time) are together.
See #58 for further details and discussion regarding this feature.
=> feat(bfdr): Canary checkbox fields

projects/BFDR/BFDR.xml, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/Canary/ClientApp/src/components/misc/info/Category.js, projects/Canary/ClientApp/src/components/misc/info/Property.js
This PR cleans up some Canary UI elements:
- Empty fields in the inspector now render as empty rather than just disappearing, which would cause categories to look empty.
- Fixed incorrectly named Property categories (such as without spaces or TODOs).
- Adds missing PropertyParams to dictionary type BFDR fields.
=> fix(bfdr): Canary UI Cleanup

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs
* adding fetalDeathRecord constructors
* adding tests for identifier fields
These fields match what is in the birthRecord, so no changes were made to getters/setters (IJE fields, FHIR extensions and paths, field types match).
=> Nvss 603 create fetaldeathrecord

projects/BFDR.Tests/BFDR.Tests.csproj, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/IJEFetalDeath_Should.cs, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/NatalityRecord_constructors.cs, projects/BFDR/NatalityRecord_fieldsAndCreateMethods.cs, projects/BFDR/NatalityRecord_submissionProperties.cs
This PR:
- Implements fixes for Child/DecendentFetus issues. FetalDeathRecords do not have a Child profile, so "Child" has been renamed to "Subject" at the NatalityRecord level and acts as a field for both Child and DecedentFetus, depending on the record type. There are new overriden RestoreReferences() and InitializeCompositionAndSubject() methods that handle setting this Subject field accordingly. A similar function is performed for the Composition as well.
- - There could be a different approach with overriden "GetSubjectProfile()" and "GetCompositionProfile()" methods which would remove the need for overriding "RestoreRefeferences()" again and remove the need for "InitializeCompositionAndSubject()". Let me know if this could be a better approach, I just wasn't sure if that could end …
=> feat(bfdr): Update Child/DecedentFetus references, Date of Registration

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/NatalityRecord_fieldsAndCreateMethods.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
COD18a1 through COD18a7 are Y/N depending on presence of code
COD18a8 is a literal text/blank
I added two class helper methods, YesNo_PresenceToIJE and YesNo_IJEToPresence, which are similar to PresenceToIJE and IJEToPresence but do not require a corresponding none-of-the-above field (these don't exist for cause of death) and are limited to only Y/N (no Unknown) per the IJE_File_Layouts. 
I also added a helper to VitalRecord_util called GetCondition which is a modification of GetObservation but for condition resources instead.
=> feat(bfdr): implement fetal death cause or condition

projects/VitalRecord.Messaging/VitalRecord.Messaging.csproj, projects/VitalRecord/CHANGELOG.md, projects/VitalRecord/VitalRecord.csproj
Update the vr version number for a new nuget package release. This new version will be used by the NVSS FHIR API in the upcoming June 2024 test event.
=> feat(vr): update version number for vr release

projects/Canary/ClientApp/src/components/Navigation.js, projects/Canary/ClientApp/src/index.js
- Fix canary failing build due to incorrect project references
- Updated the BFDR version displayed in Canary
=> fix(canary): fix project csproj project references

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/IJEFetalDeath.cs
Father birthplace fields - does not include father dob bypass edit flag, which is included in the [DOB PR](https://github.com/nightingaleproject/vital-records-dotnet/pull/123).
=> Nvss 632 father birthplace

projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/NatalityRecord_submissionProperties.cs
Implements Sex, Plurality, Set Order, Plurality Edit Flag. Code was shared between Natality and Fetal Death, except for different Patients (Child versus Decedent Fetus), so I refactored the code into getter and setter methods that could be used for both BirthRecord and FetalDeathRecord.
=> 627 sex plurality set order

.github/workflows/bfdr-test.yml, .gitignore, README.md, projects/BFDR.Tests/BFDR.Tests.csproj, projects/BFDR.Tests/run_tests.sh
- add documentation for full code coverage report generation (local) 
- add GH workflow for coverage overview in pull requests
In general we want free, open source tools that confirm test coverage when creating PRs and give us the ability to look deeper at coverage locally. The [CodeCoverageSummary](https://github.com/irongut/CodeCoverageSummary) generated in this PR was fairly straightforward to set up and is configurable. This means we can set a threshold for coverage to meet without the causing the action to fail (and whether or not it can trigger a failure at all). 
For looking closer at the coverage itself, it is useful to have a user-friendly html render of coverage information. [Coverlet ](https://github.com/coverlet-coverage/coverlet)first generates an xml file that contains …
=> ci(bfdr): add code coverage

projects/Canary/ClientApp/src/components/misc/Record.js
IJE downloadAsFile for both VRDR and BFDR was changed from .MOR file to .IJE file
=> fix(canary): change extension for IJE downloads from .MOR to .IJE

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord.json, projects/BFDR.Tests/fixtures/json/FetalDeathReport.json, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/NatalityRecord_fieldsAndCreateMethods.cs, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
FILENO and AUXNO are blank in IJEFetalDeath -- implemented. 
DOR_YR, DOR_MO, and DOR_DY property field is for birth cert -- updated the xml comment and properties to be more general
CERTIFIED_YR, CERTIFIED_MO, and CERTIFIED_DY relate to encounter birth. -- mirrored these fields in fetal death using encounter maternity instead of encounter birth
AUTOP software is using the wrong VS, should be performedNotPerformedPlanned -- fixed. Examples and test cases updated.
DSTATE investigate -- made implementation of DSTATE the same as BSTATE (using PlaceOfBirth instead of PlaceOfDelivery) 
FSEX software uses birthsexfetusvs but should use sexassignedatbirth -- checked and it was using the right vs and mapping, so no changes needed.
FETLNAME check if absence is properly handled with unknown in …
=> fix(bfdr): align fetal death software with IG

projects/BFDR.CLI/Program.cs, projects/BFDR.Messaging/BirthRecordDemographicsCodingMessage.cs, projects/BFDR.Tests/Messaging_Should.cs, projects/BFDR/NatalityRecord_constructors.cs
Fixes Demographic coding message to retrieve the full birth record bundle. Added a test to confirm the observations in a demographics coding message are all parsed when converting from fhir to json and parsing back to fhir.
=> fix(bfdr): fix convert demographic coding msg to json

projects/Canary/ClientApp/src/components/HomeScreen.js, projects/Canary/ClientApp/src/components/Navigation.js
- Publish the edge version of Canary to https://canary.fhir.nvss.cdc.gov.
- Link to Canary v4 (https://canary-v4.fhir.nvss.cdc.gov) from the home screen.
- Remove Canary version reference.
- Use IG series instead of library version when referencing to the reporting category.
=> refactor: link to Canary compatible with VRDR STU2

.github/workflows/ghcr.yml
Publish Docker image for this repository (i.e. Canary) to GitHub Container Registry, for deployment to CDC Azure.
=> ci(canary): use GitHub Container Registry to host Canary Docker image

projects/Canary/Controllers/MessagesController.cs
This pull request addresses an issue where the message inspector tools in Canary weren't displaying values for any message types.
=> fix(canary): fix record extraction bug in message inspector

projects/BFDR.CLI/Program.cs, projects/BFDR.Messaging/BFDRBaseMessage.cs, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/Messaging_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/Connectathon.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/IJEFetalDeath.cs, projects/BFDR/NatalityRecord_constructors.cs, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/Canary.Tests/RecordTests.cs, projects/Canary/Models/BirthRecordFaker.cs, projects/Canary/Models/FetalDeathFaker.cs
For Fetal Death, there are some birth-specific properties that should not be present on the fetal death side but are because those properties are in the common NatalityRecord class. This became apparent when viewing a Fetal Death Record in Canary.
This resulted in several duplicates such as:
ChildGivenName and FetusGivenName
- `DateOfBirth` vs `DateOfDelivery`
=> fix(bfdr): fix birth specific properties

projects/BFDR.Tests/fixtures/json/BasicBirthRecord2.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord2.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecordSubmissionMessage.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecordSubmissionMessage_acknowledgement.json, projects/BFDR.Tests/fixtures/json/BirthRecordDemographicsCodingMessage.json, projects/BFDR.Tests/fixtures/json/BirthRecordDemographicsCodingUpdateMessage.json, projects/BFDR.Tests/fixtures/json/BirthRecordFakeNoRace.json, projects/BFDR.Tests/fixtures/json/BirthRecordFakeWithRace.json, projects/BFDR.Tests/fixtures/json/BirthRecordR.json, projects/BFDR.Tests/fixtures/json/BirthRecordSubmissionMessage.json, projects/BFDR.Tests/fixtures/json/BirthRecordUpdateMessage.json, projects/BFDR.Tests/fixtures/json/BirthRecordZ.json, projects/BFDR.Tests/fixtures/json/MessageHeaderValidation.json, projects/BFDR.Tests/fixtures/json/MessageHeaderValidationMissingYear.json, projects/BFDR.Tests/fixtures/json/RaceEthnicityCaseRecord.json, projects/BFDR.Tests/fixtures/json/RaceEthnicityCaseRecord2.json, projects/BFDR.Tests/fixtures/xml/BasicFetalDeathRecord.xml, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord.cs, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/FetalDeathRecord.cs, projects/BFDR/FetalDeathRecord_constructors.cs, projects/BFDR/NatalityRecord_constructors.cs, projects/BFDR/NatalityRecord_fieldsAndCreateMethods.cs, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/Canary.Tests/fixtures/json/BirthRecordR.json, projects/VRDR/DeathRecord_constructors.cs
This pull request addresses NVSS-722: meta profile tags are not required to be present in FHIR documents, so should not be relied on when reading content from a VR record of any type; these changes update the code to use alternate approaches for finding content such as following references.
This pull request also provides a work around for NVSS-710. Canary uses FHIR paths to identify and display relevant sections of a FHIR document. The 4.3.0 version of the Hl7.Fhir.R4 library does not support following references in FHIR paths; until a newer version is available we make an exception to our avoidance of relying on meta profile tags since there is no other way to distinguish between the patient entries for the mother and the child.
Specific changes include
1. Updating fixtures to use …
=> fix(vr): 722 remove use of meta in the library and 710 fix mother birthplace in canary

projects/VRDR.CLI/Program.cs, projects/VRDR.CLI/Program_urimaps.cs, projects/VRDR.CLI/Program_util.cs, projects/VRDR.CLI/VRDR.CLI.csproj, projects/VRDR.Tests/fixtures/json/DeathRecord1_STU2.json, projects/VRDR.Tests/fixtures/json/DeathRecord1_STU3.json, projects/VRDR.Tests/run_tests.sh
1) Added a VRDR CLI tool to perform a difference between two JSON files that is independent of order and spacing using JsonDiffPatchDotNet.  
2) Created an STU3 variant of DeathRecord1.json that doesn't include any features not found in STU2.
3) Added a test to run_tests.sh that takes DeathRecord1_STU3.json, converts it to STU2 and back
4) Checks that the STu3 content hasn't been impacted using the usual round trip testing tools -- property by property.
5) Checks that the STU2 content created is identical to DeathRecord1_STU2.json, which is a test fixture from the vrdr-dotnet repo for STU2.2.
=> test(vrdr): add stu2 to stu3 test conversion test

projects/Canary/Models/CanaryBirthMessage.cs, projects/Canary/Models/CanaryFetalDeathMessage.cs, projects/VitalRecord.Messaging/CommonMessage.cs
Address ticket 714 Fix Unknown Properties in Canary. A couple properties were missing discriptions in the Canary Connectathon Message tool. Added the descriptions so now Canary displays the name correctly.
=> fix(canary): add descriptions for payload version id and event year

projects/BFDR.Messaging/BFDRVoidMessage.cs, projects/BFDR.Tests/Messaging_Should.cs
This PR includes:
- adding a default block count value of 1 for birth and fetal death void messages
=> feat(bfdr): adding default value 1 block count

projects/BFDR.CLI/Program.cs, projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/IJEFetalDeath_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecord2.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecordSubmissionMessage.json, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecordSubmissionMessage_acknowledgement.json, projects/BFDR/BFDR.xml, projects/BFDR/BirthRecord_constructors.cs, projects/BFDR/FetalDeathRecord_constructors.cs, projects/BFDR/NatalityRecord_constructors.cs, projects/BFDR/NatalityRecord_fieldsAndCreateMethods.cs, projects/BFDR/NatalityRecord_submissionProperties.cs, projects/VRDR/DeathRecord.xml, projects/VRDR/DeathRecord_constructors.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_constructors.cs
This PR addresses ticket [NVSS-743](https://tracker.codev.mitre.org/browse/NVSS-743)
To properly test fetal death testing with NCHS, we need to provide quality data examples with enough data for NCHS to create coded content for cause of death and demographic information. Veronique provided a list of fields to make sure are included in the test data. This PR updates the fakerecord CLI tool to add the following data to the fakerecord so we can generate quality test examples:
- Sex  
- Race and ethnicity
- Cause or condition
- Place where delivery occurs 
- Date of Birth for Mother are mapped
- Mother Residence address
The ticket also included reviewing our fetal death test fixtures and updating them to improve the data quality. Each test fixture was updated to 
- include race and ethnicity …
=> fix(bfdr): update fakerecord fetaldeath to include more data

.github/workflows/bfdr-test.yml, .github/workflows/vrdr-test.yml
Add header option to github action for posting code coverage comments for BFDR and VRDR test results. This allows both comments to coexist peacefully.
Addresses Jira issue 715.
=> ci: make BFDR and VRDR coverage comments visible simultaneously

projects/BFDR.Tests/BirthRecord_Should.cs, projects/BFDR.Tests/FetalDeathRecord_Should.cs, projects/BFDR.Tests/IJEFetalDeath_Should.cs, projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs
Many numeric IJE fields require leading zeros to pad the field to the required length. E.g. the HIN field is two characters and a length of four should be returned as "04" not "4". This PR fixes the return value for IJE field HIN and HFT in both birth and fetal death records.
Fixes #NVSS-781
=> fix(bfdr): ensure numeric fields are padded with leading zeroes

projects/BFDR.Tests/IJEFetalDeath_Should.cs, projects/BFDR/BFDR.xml, projects/BFDR/FetalDeathRecord.cs, projects/VitalRecord/CodeSystems.cs, projects/VitalRecord/VitalRecord.xml, projects/VitalRecord/VitalRecord_util.cs
The US Core IG requires conditions to include specific category codes. This PR adds problem-list-item or encounter-diagnosis category to each created condition resource. This PR also refactors the GetCondition method to extract code and category from the caller FHIR path annotation instead of requiring those to be passed as parameters.
Fixes NVSS-721
=> fix: add us core problem-list-item category to created FHIR conditions

.gitignore, projects/BFDR.Messaging/BFDRBaseMessage.cs, projects/BFDR.Tests/BFDR.Tests.csproj, projects/BFDR.Tests/Messaging_Should.cs, projects/BFDR.Tests/fixtures/json/BasicFetalDeathRecordSubmissionMessageNoBundle.json, projects/BFDR.Tests/fixtures/json/BirthRecordDemographicsCodingMessageNoNatality.json, projects/BFDR.Tests/fixtures/json/BirthRecordErrorMessageNoOperationOutcome.json, projects/BFDR.Tests/fixtures/json/BirthRecordSubmissionMessageNoBundle.json, projects/BFDR.Tests/fixtures/json/BirthRecordVoidMessageWithoutBlockCount.json, projects/BFDR.Tests/fixtures/json/FetalDeathAcknowledgementMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathCodedCauseMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathCodedCauseMessageNoBundle.json, projects/BFDR.Tests/fixtures/json/FetalDeathCodedCauseUpdateMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathDemographicsCodingUpdateMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathErrorMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathRecordStatusMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathUpdateMessage.json, projects/BFDR.Tests/fixtures/json/FetalDeathVoidMessage.json, projects/BFDR.Tests/fixtures/json/HeadlessMessage.json, projects/BFDR.Tests/fixtures/json/InvalidMessage.json, projects/BFDR.Tests/fixtures/json/MissingMessage.json
Add tests to BFDR.Messaging classes such that reported test line coverage is as close to 100% as possible. In most cases, 100% line coverage is reached. Exceptions to this are:
BFDRBaseMessage
33-35: Unreachable. The condition on line 32 can't be met due to an identical condition in the base constructor.
281-284, 287-290: Unreachable. These classes are abstract, so the message type will never match these values.
BFDRAcknowledgementMessage
117-120: Unreachable. Header.Response is guaranteed to be non-null here.
BFDRParentalDemographicsCodingMessage
256-259: Unreachable. Header.Response is guaranteed to be non-null here.
BFDRErrorMessage
135-138: Unreachable. Header.Response is guaranteed to be non-null here.
Addresses Jira issue 763.
=> test(bfdr): add tests for bfdr messaging classes

projects/BFDR.Tests/NatalityData_Should.cs, projects/BFDR/IJEBirth.cs, projects/BFDR/IJEFetalDeath.cs, projects/VRDR.STU2.Convert/Program.cs, projects/VRDR/DeathRecord.xml, projects/VRDR/IJEMortality.cs, projects/VitalRecord/IJE.cs, projects/VitalRecord/VitalRecord.xml
This PR updates IJE properties whose getter could return strings that don't match the IJE field length, adding padding as necessary. A new helper method (LeftJustifiedValue) is used to consolidate handling of multivalued FHIR attributes such as given names. An existing VRDR helper is moved to the IJE base class for use in BFDR.
Fixes #NVSS-787
=> fix(bfdr): ensure IJE fields return strings of the correct length

projects/Canary/ClientApp/src/components/misc/Getter.js
The Getter component is used to provide a text area and display a list of issues. Display any error returned by the API server using the list of issues.
The original goal of this task was to do a more complete overhaul of error messages displayed in Canary. But, as I learned more about the variety of errors and API routes, this seemed less feasible. So for this PR, I reduced the scope to the `Getter` component. Other considerations for errors shown in Canary include:
* Errors returned when using the Connectathon component, as various parts of the interface are hidden/shown throughout the usage of the component.
* Uncaught exceptions from API routes. Some exceptions are from data errors that the user can fix, but other errors indicate problems that the user cannot fix (and the user should …
=> feat(canary): show errors for text area inputs below the text area

projects/BFDR.CLI/README.md, projects/BFDR/README.md
Details about using BFDR.CLI are moved to a new README file in the BFDR.CLI directory.
Update some section headers to avoid repeating headers. Assorted minor text revisions.
The Return Coding Example is left blank in this change, as it is being added in a different branch.
Addresses Jira issue 779.
=> docs(bfdr): add table of contents, move cli information
